build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.18
  amd64: ghcr.io/home-assistant/amd64-base:3.18
  armhf: ghcr.io/home-assistant/armhf-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
  i386: ghcr.io/home-assistant/i386-base:3.18
labels:
  org.opencontainers.image.title: "Shopping Scanner"
  org.opencontainers.image.description: "Barcode scanner for Home Assistant shopping lists"
  org.opencontainers.image.source: "https://github.com/Siweaver1971/ha-shopping-scanner"
  org.opencontainers.image.licenses: "MIT"
args: {}